replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/curser-project/my-artifact-repo/myapp
  tag: 7929939-74

service:
  type: LoadBalancer
  port: 80

env:
  APP_NAME: myapp
  APP_ENV: Development
