replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/curser-project/my-artifact-repo/myapp
  tag: 4b78b52-40

service:
  type: ClusterIP
  port: 80

env:
  APP_NAME: myapp
  APP_ENV: production
